import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/common/Sidebar";
import { poppins } from "@/styles/font";
import Navbar from "@/components/common/Navbar";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Mira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased h-screen flex ${poppins.className} overflow-hidden`}
      >
        <Providers>
          <Sidebar />
          <div className="grow flex flex-col overflow-y-auto">
            <Navbar />
            <div className="grow bg-[#f6f6f8]">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
