import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/common/Sidebar";
import { poppins } from "@/styles/font";
import Navbar from "@/components/common/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased h-screen flex ${poppins.className} overflow-hidden`}
      >
        <Sidebar />
        <div className="grow overflow-y-auto">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
