import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/styles/font";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Mira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased h-screen flex ${poppins.className} overflow-hidden`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
